#pragma once

#include "stdafx.h"

enum GameplayStates
{
	NULL_GAMEPLAY_STATE = 0,

	ABILITY_GAMEPLAY_STATE,
	ATTACK_GAMEPLAY_STATE,
	MOVE_GAMEPLAY_STATE,
	SELECTION_GAMEPLAY_STATE,
	TRANSITION_GAMEPLAY_STATE
};